---
- name: Generar respaldo del running-config del CSR1000v
  hosts: routers
  gather_facts: no
  tasks:
    - name: Ejecutar comando show running-config
      cisco.ios.ios_command:
        commands: show running-config
      register: config_output

    - name: Guardar la configuracion en un archivo local
      copy:
        content: "{{ config_output.stdout[0] }}"
        dest: "./respaldo_router_running.txt"

    - name: Confirmar creacion del respaldo
      debug:
        msg: "El respaldo ha sido guardado exitosamente en ./respaldo_router_running.txt"
